# Generated by Django 3.2.5 on 2021-08-01 05:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTrack',
            fields=[
                ('currentDay', models.IntegerField(blank=True, default=1, null=True)),
                ('paused', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
