# Generated by Django 3.2.5 on 2021-07-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('level 0', 'Beginner'), ('level 1', 'Medium'), ('level 2', 'Hard'), ('level 3', 'Expert')], default='level 0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='dayNo',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
