# Generated by Django 3.2.5 on 2021-07-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210731_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Level 0'), ('Medium', 'Level 1'), ('Hard', 'Level 2'), ('Expert', 'Level 3')], default='Level 0', max_length=20),
        ),
    ]
