# Generated by Django 3.2.5 on 2021-07-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='space_cmplx',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_cmplx',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
