# Generated by Django 3.2.5 on 2021-08-04 08:28

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
